# Project-wide Gradle settings for CareGrid React Native Android
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.18.8-hotspot
org.gradle.vfs.watch=false
android.useAndroidX=true
android.enableJetifier=true
# Enable Hermes JavaScript engine
hermesEnabled=true

# New Architecture (Fabric & TurboModules) flag
newArchEnabled=false
